export const Actions = {
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
  MOVE_LEFT: "MOVE_LEFT",
  MOVE_RIGHT: "MOVE_RIGHT",
  JUMP: "JUMP",
  INTERACT: "INTERACT",
  TOGGLE_PANEL: "TOGGLE_PANEL",
  TOGGLE_CONTROLS: "TOGGLE_CONTROLS",
  CLOSE: "CLOSE",
  UI_NAV_PREV: "UI_NAV_PREV",
  UI_NAV_NEXT: "UI_NAV_NEXT",
  UI_NAV_UP: "UI_NAV_UP",
  UI_NAV_DOWN: "UI_NAV_DOWN",
  UI_NAV_LEFT: "UI_NAV_LEFT",
  UI_NAV_RIGHT: "UI_NAV_RIGHT",
  CONFIRM: "CONFIRM",
  CYCLE_FORWARD: "CYCLE_FORWARD",
  CYCLE_BACKWARD: "CYCLE_BACKWARD",
  BEGIN_GAME: "BEGIN_GAME",
} as const;

export type Action = (typeof Actions)[keyof typeof Actions];

export const DefaultKeymap: Record<string, readonly string[]> = {
  [Actions.MOVE_UP]: ["W", "UP"],
  [Actions.MOVE_DOWN]: ["S", "DOWN"],
  [Actions.MOVE_LEFT]: ["A", "LEFT"],
  [Actions.MOVE_RIGHT]: ["D", "RIGHT"],
  [Actions.JUMP]: ["SPACE"],
  [Actions.INTERACT]: ["E"],
  [Actions.TOGGLE_PANEL]: ["TAB"],
  [Actions.TOGGLE_CONTROLS]: ["Q"],
  [Actions.CLOSE]: ["ESC"],
  [Actions.UI_NAV_PREV]: ["W", "UP", "A", "LEFT"],
  [Actions.UI_NAV_NEXT]: ["S", "DOWN", "D", "RIGHT"],
  [Actions.UI_NAV_UP]: ["W", "UP"],
  [Actions.UI_NAV_DOWN]: ["S", "DOWN"],
  [Actions.UI_NAV_LEFT]: ["A", "LEFT"],
  [Actions.UI_NAV_RIGHT]: ["D", "RIGHT"],
  [Actions.CONFIRM]: ["SPACE", "ENTER"],
  [Actions.CYCLE_FORWARD]: ["UP", "RIGHT", "W", "D"],
  [Actions.CYCLE_BACKWARD]: ["DOWN", "LEFT", "S", "A"],
  [Actions.BEGIN_GAME]: ["SPACE"],
};
